"""empty message

Revision ID: aa37c5828050
Revises: 78f4f0046893
Create Date: 2023-07-31 22:42:48.887095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa37c5828050'
down_revision = '78f4f0046893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('user_username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('user_phone_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('user_is_active', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_username'])
        batch_op.create_unique_constraint(None, ['user_email'])
        batch_op.create_unique_constraint(None, ['user_phone_number'])
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('user_is_active')
        batch_op.drop_column('user_phone_number')
        batch_op.drop_column('user_username')
        batch_op.drop_column('user_password')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
